# .pre-commit-config.yaml
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

-   repo: local
    hooks:
    -   id: pytest
        name: Run pytest
        entry: python -m pipenv run pytest --assert=plain
        language: system
        types: [python]
        pass_filenames: false
        always_run: true
